import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1600, height: 900 } })
await page.goto('http://localhost:5173/?from=48.8920,2.2380&at=09:00', { waitUntil: 'networkidle', timeout: 60000 })
await page.waitForSelector('text=arrêts atteignables', { timeout: 60000 })
const before = (await page.locator('text=arrêts atteignables').textContent())?.trim()
await page.locator('select').first().selectOption('arrive')
await page.waitForTimeout(1500)
const after = (await page.locator('text=arrêts atteignables').textContent())?.trim()
console.log('DEPART:', before)
console.log('ARRIVE:', after)
console.log('URL_DIR:', page.url().includes('d=arrive'))
await browser.close()
