import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1600, height: 900 } })
const errors = []
page.on('pageerror', (e) => errors.push(String(e)))
await page.goto('http://localhost:5173/', { waitUntil: 'networkidle', timeout: 60000 })
const t0 = Date.now()
await page.locator('input[placeholder*="Adresse"]').pressSequentially('10 rue de rivo', { delay: 60 })
await page.waitForSelector('text=Rue de Rivoli', { timeout: 10000 })
console.log('SUGGESTION_LATENCY_MS (typing incl.):', Date.now() - t0)
await page.screenshot({ path: 'smoke-search.png' })
await page.keyboard.press('ArrowDown')
await page.keyboard.press('Enter')
await page.waitForSelector('text=arrêts atteignables', { timeout: 30000 })
console.log('MARKER_PLACED:', await page.locator('.leaflet-marker-icon').count())
console.log('ERRORS:', errors.length ? errors.join('|') : 'none')
await browser.close()
